#--------- This file is automatically generated by LSST's sconsUtils ---------#
__version__ = 'f154f25'
__repo_version__ = 'f154f25'
__repo_version__ = 'f154f25'
__fingerprint__ = 'f154f2562b1f63583b09005ed30594bb2cb774c8'
__dependency_versions__ = {
}
__all__ = ('__version__', '__repo_version__', '__repo_version__', '__fingerprint__', '__dependency_versions__')
